name: Check Dependency Updates
on:
  schedule:
    - cron: "37 13 * * SAT"
  workflow_dispatch:
jobs:
  dependency-updates:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v2
      - name: Use Java 11
        uses: actions/setup-java@v1
        with:
          java-version: '11'
      - name: Copy CI gradle.properties
        run: mkdir -p ~/.gradle ; cp .github/ci-gradle.properties ~/.gradle/gradle.properties
      - name: Check Dependency Updates
        uses: burrunan/gradle-cache-action@v1
        with:
          gradle-dependencies-cache-key: buildSrc/**/Dependencies.kt
          save-local-build-cache: false # Disable caching of ~/.gradle/caches/build-cache-*
          gradle-distribution-sha-256-sum-warning: false
          read-only: true
          arguments: dependencyUpdates
      - name: Log dependency update report
        run: cat build/dependencyUpdates/dependency_update_report.txt
      - name: 💌 Send email report
        if: ${{ github.event_name == 'schedule' }}
        uses: actions/github-script@v3
        env:
          MAIL_USERNAME: ${{ secrets.MAIL_USERNAME }}
          MAIL_PASSWORD: ${{ secrets.MAIL_PASSWORD }}
        with:
          script: |
            const scriptPath = '/./.github/scripts/dependency-update-report-mail-sender.js'
            const script = require(`${process.env.GITHUB_WORKSPACE}${scriptPath}`)
            script({ })
      - name: Share dependency update reports
        uses: actions/upload-artifact@v2
        with:
          name: dependency-update-reports
          path: build/dependencyUpdates
